### Успешная регистрация
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "name": "TestUser111",
  "email": "test111@example.com",
  "password": "secret122"
}

###

### Ошибка валидации (короткий пароль)
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "name": "BadUser",
  "email": "bad@example.com",
  "password": "123"
}

###

### Пустое имя + невалидный email
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "name": "",
  "email": "notanemail",
  "password": "validpass"
}

### Успешный вход
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "secret12"
}

###

### Ошибка валидации (некорректный email)
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "notanemail",
  "password": "123"
}

###

### Проверка авторизации пользователя (GET /users/me)
GET http://localhost:3000/users/me
Authorization: Bearer {{access_token}}

###
### Проверка авторизации пользователя (GET /users/check)
GET http://localhost:3000/users/check
Authorization: Bearer {{access_token}}

###
